module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "build",
        "Build",
        "chore",
        "Chore",
        "ci",
        "CI",
        "docs",
        "Docs",
        "feat",
        "Feat",
        "fix",
        "Fix",
        "perf",
        "Perf",
        "refactor",
        "Refactor",
        "revert",
        "Revert",
        "style",
        "Style",
        "test",
        "Test",
      ],
    ],
    "type-case": [0],
  },
};
