import { Quiz } from "../util/appwrite";

const quizData: Quiz[] = [
  {
    $id: "1sadf2fdgsfdgfsdg3",
    $collectionId: "123",
    $databaseId: "123",
    $createdAt: "123",
    $updatedAt: "123",
    $permissions: ["123"],
    title: "Capitals of Europe",
    type: "blur",
    theme: "Geography",
    questions: [
      {
        id: 1,
        question: "What is the capital of France?",
        answers: ["Paris", "London", "Berlin", "Madrid"],
        correctAnswer: "Paris",
      },
      {
        id: 2,
        question: "What is the capital of Germany?",
        answers: ["Paris", "London", "Berlin", "Madrid"],
        correctAnswer: "Berlin",
      },
      {
        id: 3,
        question: "What is the capital of Spain?",
        answers: ["Paris", "London", "Berlin", "Madrid"],
        correctAnswer: "Madrid",
      },
    ],
    previewUrl:
      "https://cdn.britannica.com/67/367-050-CCA16287/Europe-political-boundaries-continent.jpg",
    creatorId: "123",
    creatorUsername: "Fubuki",
  },
  {
    $id: "12sadf3",
    $collectionId: "123",
    $databaseId: "123",
    $createdAt: "123",
    $updatedAt: "123",
    $permissions: ["123"],
    title: "Capitals of Asia",
    type: "blur",
    theme: "Geography",
    questions: [
      {
        id: 1,
        question: "What is the capital of Japan?",
        answers: ["Tokyo", "Beijing", "Seoul", "Bangkok"],
        correctAnswer: "Tokyo",
      },
      {
        id: 2,
        question: "What is the capital of China?",
        answers: ["Tokyo", "Beijing", "Seoul", "Bangkok"],
        correctAnswer: "Beijing",
      },
      {
        id: 3,
        question: "What is the capital of South Korea?",
        answers: ["Tokyo", "Beijing", "Seoul", "Bangkok"],
        correctAnswer: "Seoul",
      },
    ],
    previewUrl:
      "https://cdn.britannica.com/20/5920-050-5A543266/Asia-political-boundaries-continent.jpg",
    creatorId: "123",
    creatorUsername: "Fubuki",
  },
  {
    $id: "1sadf23",
    $collectionId: "123",
    $databaseId: "123",
    $createdAt: "123",
    $updatedAt: "123",
    $permissions: ["123"],
    title: "Capitals of Africa",
    type: "blur",
    theme: "Geography",
    questions: [
      {
        id: 1,
        question: "What is the capital of Nigeria?",
        answers: ["Lagos", "Cairo", "Nairobi", "Abuja"],
        correctAnswer: "Abuja",
      },
      {
        id: 2,
        question: "What is the capital of Egypt?",
        answers: ["Lagos", "Cairo", "Nairobi", "Abuja"],
        correctAnswer: "Cairo",
      },
      {
        id: 3,
        question: "What is the capital of Kenya?",
        answers: ["Lagos", "Cairo", "Nairobi", "Abuja"],
        correctAnswer: "Nairobi",
      },
    ],
    previewUrl:
      "https://cdn.britannica.com/63/5363-050-90082F00/Africa-political-boundaries-continent.jpg",
    creatorId: "123",
    creatorUsername: "Fubuki",
  },
  {
    $id: "123dsfgsdfg",
    $collectionId: "123",
    $databaseId: "123",
    $createdAt: "123",
    $updatedAt: "123",
    $permissions: ["123"],
    title: "Capitals of North America",
    type: "blur",
    theme: "Geography",
    questions: [
      {
        id: 1,
        question: "What is the capital of Canada?",
        answers: ["Toronto", "Ottawa", "Vancouver", "Montreal"],
        correctAnswer: "Ottawa",
      },
      {
        id: 2,
        question: "What is the capital of Mexico?",
        answers: ["Toronto", "Ottawa", "Vancouver", "Mexico City"],
        correctAnswer: "Mexico City",
      },
      {
        id: 3,
        question: "What is the capital of the United States?",
        answers: ["Toronto", "Ottawa", "Washington D.C.", "Montreal"],
        correctAnswer: "Washington D.C.",
      },
    ],
    previewUrl:
      "https://c.files.bbci.co.uk/4616/live/d710a6a0-d4b0-11ef-9fd6-0be88a764111.jpg",
    creatorId: "123",
    creatorUsername: "Fubuki",
  },
  {
    $id: "1bdfsbfdsb23",
    $collectionId: "123",
    $databaseId: "123",
    $createdAt: "123",
    $updatedAt: "123",
    $permissions: ["123"],
    title: "Capitals of South America",
    type: "blur",
    theme: "Geography",
    questions: [
      {
        id: 1,
        question: "What is the capital of Brazil?",
        answers: ["Buenos Aires", "Santiago", "Lima", "Brasília"],
        correctAnswer: "Brasília",
      },
      {
        id: 2,
        question: "What is the capital of Argentina?",
        answers: ["Buenos Aires", "Santiago", "Lima", "Brasília"],
        correctAnswer: "Buenos Aires",
      },
      {
        id: 3,
        question: "What is the capital of Chile?",
        answers: ["Buenos Aires", "Santiago", "Lima", "Brasília"],
        correctAnswer: "Santiago",
      },
    ],
    previewUrl:
      "https://cdn.britannica.com/86/3886-050-2785B482/South-America-political-continent.jpg",
    creatorId: "123",
    creatorUsername: "Fubuki",
  },
  {
    $id: "1dfbsfdb23",
    $collectionId: "123",
    $databaseId: "123",
    $createdAt: "123",
    $updatedAt: "123",
    $permissions: ["123"],
    title: "Why am I so broke",
    type: "blur",
    theme: "Depression",
    questions: [],
    previewUrl:
      "https://miro.medium.com/v2/resize:fit:1400/1*7HTzbeMGCDnDvdV-IrSYZA.jpeg",
    creatorId: "123",
    creatorUsername: "Fubuki",
  },
  {
    $id: "12dfsbsfdb",
    $collectionId: "123",
    $databaseId: "123",
    $createdAt: "123",
    $updatedAt: "123",
    $permissions: ["123"],
    title: "Best Among us race",
    type: "blur",
    theme: "Philosophy",
    questions: [],
    previewUrl:
      "https://media.wired.com/photos/620581d7c228dc232641feaa/16:9/w_2400,h_1350,c_limit/Games-Innersloth-Among-Us-Key-Art.jpg",
    creatorId: "123",
    creatorUsername: "Fubuki",
  },
  {
    $id: "1dsfbfsdbdfs23",
    $collectionId: "123",
    $databaseId: "123",
    $createdAt: "123",
    $updatedAt: "123",
    $permissions: ["123"],
    title: "The size of your Mom",
    type: "blur",
    theme: "Science",
    questions: [],
    previewUrl:
      "https://s.abcnews.com/images/Technology/whale-gty-jt-191219_hpMain.jpg",
    creatorId: "123",
    creatorUsername: "Fubuki",
  },
  {
    $id: "12asdvrewavservd3",
    $collectionId: "123",
    $databaseId: "123",
    $createdAt: "123",
    $updatedAt: "123",
    $permissions: ["123"],
    title: "The best pizza in Austin",
    type: "blur",
    theme: "Austin Pizza",
    questions: [],
    previewUrl:
      "https://www.foodandwine.com/thmb/Wd4lBRZz3X_8qBr69UOu2m7I2iw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/classic-cheese-pizza-FT-RECIPE0422-31a2c938fc2546c9a07b7011658cfd05.jpg",
    creatorId: "123bvcbvsdfbdfsbdfsb",
    creatorUsername: "Fubuki",
  },
  {
    $id: "12edrgzxfdbv3",
    $collectionId: "123",
    $databaseId: "123",
    $createdAt: "123",
    $updatedAt: "123",
    $permissions: ["123"],
    title: "Why does your nose run but your feet smell?",
    type: "blur",
    theme: "English",
    questions: [],
    previewUrl:
      "https://api.hub.jhu.edu/factory/sites/default/files/styles/landscape/public/depression-hub.jpg",
    creatorId: "1dfsbfsdbfsdb23",
    creatorUsername: "Fubuki",
  },
  {
    $id: "12vdsagfwgdasbgv3",
    $collectionId: "123",
    $databaseId: "123",
    $createdAt: "123",
    $updatedAt: "123",
    $permissions: ["123"],
    title: "Is cereal soup?",
    type: "blur",
    theme: "English",
    questions: [],
    previewUrl:
      "https://media.gq-magazine.co.uk/photos/5d1390269a22c2b6ef9478f3/16:9/w_2560%2Cc_limit/depression-gq-7aug18_istock_b.jpg",
    creatorId: "12sdafbdsfbdsfbdfsb3",
    creatorUsername: "Fubuki",
  },
  {
    $id: "12bnfdsbfsb3",
    $collectionId: "123",
    $databaseId: "123",
    $createdAt: "123",
    $updatedAt: "123",
    $permissions: ["123"],
    title: "Does a straw have one hole or two?",
    type: "blur",
    theme: "English",
    questions: [],
    previewUrl:
      "https://www.logansportmemorial.org/wp-content/uploads/Depression.jpeg",
    creatorId: "12dsafasdfdsaf3",
    creatorUsername: "Fubuki",
  },
];

export default quizData;
